
participant_ids:
  - "1"
  - "2"

1:
  modality_order:
    - "pref"
    - "demo"
  pref:
    - "slow"
    - "medium"
    - "fast"
  demo:
    - "medium"
    - "fast"
    - "slow"
2:
  modality_order:
    - "demo"
    - "pref"
  pref:
    - "fast"
    - "medium"
    - "slow"
  demo:
    - "slow"
    - "fast"
    - "medium"
4:
  modality_order:
    - "demo"
    - "pref"
  pref:
    - "medium"
    - "slow"
    - "fast"
  demo:
    - "fast"
    - "slow"
    - "medium"
5:
  modality_order:
    - "pref"
    - "demo"
  pref:
    - "fast"
    - "slow"
    - "medium"
  demo:
    - "fast"
    - "medium"
    - "slow"